#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 22 22:11:10 2022

@author: chriswang
"""

#constrant propogation 
#arc3 consistency algorithm
#import csp
#csp will contain variables, domains, and constraints
